Allowed instructors
tamu-edu-students/Faculty-Teaching-Assignment pull request #54
Opened 2024-11-13 20:44 UTC by Kingofikings441

When predefining a course, can only assign eligible teachers. The form also sorts by preference then bandwidth(how many courses they can still take)

2024-11-14 05:36 UTC, Naviunni requested changes
Please add some cucumber tests as well

2024-11-14 05:36 UTC, Naviunni commented on app/controllers/room_bookings_controller.rb
> +    # end.reverse
Please remove these comments

2024-11-14 05:36 UTC, Naviunni commented on app/controllers/room_bookings_controller.rb
> +    @schedule = Schedule.find(params[:schedule_id])
create a private set_schedule function similar to other controllers

2024-11-14 05:36 UTC, Naviunni commented on app/controllers/room_bookings_controller.rb
> +    # redirect_back(fallback_location: room_bookings_path)
remove comment

2024-11-14 05:36 UTC, Naviunni commented on app/controllers/room_bookings_controller.rb
> +
Same, please remove these comments

2024-11-15 21:30 UTC, Kingofikings441 commented on app/controllers/room_bookings_controller.rb
> +
removed

2024-11-15 21:30 UTC, Kingofikings441 commented on app/controllers/room_bookings_controller.rb
> +    # redirect_back(fallback_location: room_bookings_path)
removed

2024-11-15 21:30 UTC, Kingofikings441 commented on app/controllers/room_bookings_controller.rb
> +    @schedule = Schedule.find(params[:schedule_id])
created

2024-11-15 21:30 UTC, Kingofikings441 commented on app/controllers/room_bookings_controller.rb
> +    # end.reverse
removed

2024-11-15 22:03 UTC, wahibkapdi requested changes

2024-11-15 22:03 UTC, wahibkapdi commented on app/controllers/room_bookings_controller.rb
> +    @section = Section.find_by(id: @booking.section_id)
Sections are no longer part of our flow.

2024-11-15 22:03 UTC, wahibkapdi commented on app/controllers/room_bookings_controller.rb
> +    @section = Section.find_by(id: @booking.section_id)
RoomBookings are directly linked to courses now.

2024-11-15 22:03 UTC, wahibkapdi commented on app/helpers/room_bookings_helper.rb
> +    course_id = booking.section.course.id
Same as above.

2024-11-15 22:03 UTC, wahibkapdi commented on app/controllers/room_bookings_controller.rb
>      params.require(:room_booking).permit(:room_id, :time_slot_id, :is_available, :is_lab, :instructor_id, :section_id)
Same as above.

2024-11-15 22:03 UTC, wahibkapdi commented on app/views/room_bookings/index.html.erb
>                                  <%= booking.section.seats_alloted %>
Same as above.

2024-11-15 22:03 UTC, wahibkapdi commented on app/views/room_bookings/index.html.erb
> +                                                    eligible_instructors(@schedule, booking).map { |instructor| ["#{instructor.first_name} #{instructor.last_name} #{get_preference(instructor, booking
Same as above.

2024-11-21 23:27 UTC, closed without merging

2024-11-21 23:27 UTC, wahibkapdi commented
Closing as another PR with the required changes has been merged.